<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Roslynator.Analyzers" Version="4.13.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Gadec.Common\Gadec.Common.csproj" />
		<ProjectReference Include="..\GadecCAD.Data\GadecCAD.Data.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Helpers\" />
	</ItemGroup>

</Project>
